### ISSUE TITLE
Vue-spinner usage in vue-resource interceptor

### ISSUE THREAD

**Issue by franc014** [yyx990803/vue-resource#406]
Hi, 
I'm using vue-resource and I'd like to use vue-spinner (https://github.com/greyby/vue-spinner) inside interceptors to show/hide the spinner on any ajax request. I don't know if it's possible to reference a vue-spinner component inside the interceptor. I have done the following but with no success: (I'm using vueify)

```
var PulseLoader = require('vue-spinner/dist/vue-spinner.min').PulseLoader;

Vue.http.interceptors.push((request, next) => {
    this.loading = true;
   next((response) => {
        this.loading = false;
    });
});

new Vue({
    el: '#grid-manager',
   components: { 'pulse-loader': PulseLoader},

  ....and in the root vue instance i have:

<pulse-loader :loading="loading" :color="color" :size="size"></pulse-loader>

```

Thanks!

**Comment by giorgio1987** [comment]
Hi, 
you can use this: [nprogress](https://github.com/rstacruz/nprogress)

`import NProgress from 'nprogress'
import 'nprogress/nprogress.css'

Vue.http.interceptors.push((request, next) => {
    NProgress.start();
    next((response)=>{
        NProgress.done();
      });
});`

**Comment by franc014** [comment]
Thanks @gg87 . I think this is a better solution than using vue-spinner.
